### ISSUE TITLE
File already exists error

### ISSUE THREAD

**Issue by NickGaens** [rconradharris/reddit-background#25]
When executing reddit-background using the CLI, it will throw the following exception:

```
Traceback (most recent call last):
  File "./reddit-background", line 791, in <module>
    main()
  File "./reddit-background", line 787, in main
    desktop.set_background(paths[0])
  File "./reddit-background", line 460, in set_background
    os.symlink(path, link_name)
OSError: [Errno 17] File exists
```

**Comment by rconradharris** [comment]
@NickGaens If you still have that failure, could you run the program with `-vv` and paste the results?

**Comment by NickGaens** [comment]
Command: `Nicks-MacBook-Pro:bin nickgaens$ ./reddit-background/reddit-background {seasonal} -vv`
Output:
```
Nicks-MacBook-Pro:bin nickgaens$ ./reddit-background/reddit-background {seasonal} -vv
Deleting desktop symlink '/Users/nickgaens/Desktop/April Morning [2928 × 1952] [OC].jpg'
Deleting desktop symlink '/Users/nickgaens/Desktop/Pink Flowers in Regents Park, London [OC][6000x4000].jpg'
Total candidate images: 13
   Ranking     Score    Aspect       Res    Reddit    Jitter Title
========================================================================================================================
        13      0.46      0.83      0.15      0.83      0.01 Knightville, South Portland, Maine [OC] [3264x2446]
        12      0.46      0.50      0.28      0.86      0.19 Nighttime Light, [1080 x 1350].
        11      0.48      0.94      0.13      0.80      0.07 Iris in the garden [oc] [2038x1365]
        10      0.49      0.82      0.17      0.77      0.19 [1012x767] [OC] Sweden, stockholm suburbs hässelby
         9      0.50      0.94      1.00      0.00      0.07 Star Shaped Lover's, in London [OC] [6000X4000]
         8      0.53      0.90      0.40      0.65      0.18 Spring in the Arctic [oc] [1920x1080]
         7      0.58      0.47      1.00      0.83      0.04 2448x3264 Spring is here. When the temp is just right, it can...
         6      0.62      0.94      0.51      0.77      0.25 A blooming California purplehead field in Ventura County [200...
         5      0.67      0.94      1.00      0.61      0.12 Hidden in Holland Park, London [OC][6000x4000]
         4      0.69      0.94      1.00      0.61      0.20 Emerging to reveal its beauty, Regents Park, London[OC] [6000...
         3      0.73      0.94      1.00      0.80      0.17 Birds eye view of a bright flower [OC] [6000X4000]
         2      0.77      0.94      1.00      0.92      0.22 Pink Flowers in Regents Park, London [OC][6000x4000]
         1      0.79      0.94      1.00      1.00      0.22 April Morning [2928 × 1952] [OC]
Number of images to download: 1
'April Morning [2928 × 1952] [OC].jpg' already downloaded, skipping...
Downloading 'https://i.redditmedia.com/8LqraEwidzGzNUgj3827x7XoLAoikzUwk0glq5b8caA.jpg?s=9d7395adc6bfcd36048c77cbb52e3a49' to '/Users/nickgaens/Reddit Backgrounds/Desktop 1/Pink Flowers in Regents Park, London [OC][6000x4000].jpg'
Setting background for desktop 1
Total candidate images: 13
   Ranking     Score    Aspect       Res    Reddit    Jitter Title
========================================================================================================================
        13      0.48      0.75      0.38      0.72      0.07 Knightville, South Portland, Maine [OC] [3264x2446]
        12      0.48      0.74      0.43      0.72      0.04 [1012x767] [OC] Sweden, stockholm suburbs hässelby
        11      0.52      0.84      1.00      0.00      0.25 Star Shaped Lover's, in London [OC] [6000X4000]
        10      0.54      0.84      0.34      0.76      0.23 Iris in the garden [oc] [2038x1365]
         9      0.56      0.45      0.70      0.87      0.20 Nighttime Light, [1080 x 1350].
         8      0.58      0.42      1.00      0.84      0.06 2448x3264 Spring is here. When the temp is just right, it can...
         7      0.62      0.84      1.00      0.58      0.06 Hidden in Holland Park, London [OC][6000x4000]
         6      0.68      1.00      1.00      0.68      0.05 Spring in the Arctic [oc] [1920x1080]
         5      0.69      0.84      1.00      0.76      0.14 A blooming California purplehead field in Ventura County [200...
         4      0.70      0.84      1.00      0.72      0.22 Emerging to reveal its beauty, Regents Park, London[OC] [6000...
         3      0.71      0.84      1.00      0.80      0.20 Birds eye view of a bright flower [OC] [6000X4000]
         2      0.72      0.84      1.00      1.00      0.05 Pink Flowers in Regents Park, London [OC][6000x4000]
         1      0.73      0.84      1.00      1.00      0.07 April Morning [2928 × 1952] [OC]
Number of images to download: 1
Downloading 'https://i.redditmedia.com/Oj7SezHAgVDZsUveq9wpcmGORTtnV9N-ukhReB27iow.jpg?s=db891ca4f0ff5138a8c30624b75f30de' to '/Users/nickgaens/Reddit Backgrounds/Desktop 2/April Morning [2928 × 1952] [OC].jpg'
Setting background for desktop 2
Total candidate images: 13
   Ranking     Score    Aspect       Res    Reddit    Jitter Title
========================================================================================================================
        13      0.48      0.74      0.43      0.74      0.03 [1012x767] [OC] Sweden, stockholm suburbs hässelby
        12      0.50      0.84      1.00      0.00      0.16 Star Shaped Lover's, in London [OC] [6000X4000]
        11      0.52      0.84      0.34      0.74      0.17 Iris in the garden [oc] [2038x1365]
        10      0.53      0.45      0.70      0.85      0.12 Nighttime Light, [1080 x 1350].
         9      0.54      0.75      0.38      0.78      0.24 Knightville, South Portland, Maine [OC] [3264x2446]
         8      0.58      0.42      1.00      0.85      0.04 2448x3264 Spring is here. When the temp is just right, it can...
         7      0.66      0.84      1.00      0.61      0.18 Hidden in Holland Park, London [OC][6000x4000]
         6      0.66      0.84      1.00      0.70      0.11 Birds eye view of a bright flower [OC] [6000X4000]
         5      0.67      0.84      1.00      0.61      0.22 Emerging to reveal its beauty, Regents Park, London[OC] [6000...
         4      0.68      0.84      1.00      0.70      0.17 A blooming California purplehead field in Ventura County [200...
         3      0.71      1.00      1.00      0.66      0.18 Spring in the Arctic [oc] [1920x1080]
         2      0.71      0.84      1.00      0.94      0.06 Pink Flowers in Regents Park, London [OC][6000x4000]
         1      0.73      0.84      1.00      1.00      0.09 April Morning [2928 × 1952] [OC]
Number of images to download: 1
Downloading 'https://i.redditmedia.com/Oj7SezHAgVDZsUveq9wpcmGORTtnV9N-ukhReB27iow.jpg?s=db891ca4f0ff5138a8c30624b75f30de' to '/Users/nickgaens/Reddit Backgrounds/Desktop 3/April Morning [2928 × 1952] [OC].jpg'
Setting background for desktop 3
Traceback (most recent call last):
  File "./reddit-background/reddit-background", line 791, in <module>
    main()
  File "./reddit-background/reddit-background", line 787, in main
    desktop.set_background(paths[0])
  File "./reddit-background/reddit-background", line 460, in set_background
    os.symlink(path, link_name)
OSError: [Errno 17] File exists
```

**Comment by NickGaens** [comment]
Note: running the binary again from within the `reddit-backgrounds` directory didn't give the error this time!

Command: `Nicks-MacBook-Pro:reddit-background nickgaens$ ./reddit-background {seasonal} -vv
`
Output: 
```
Deleting desktop symlink '/Users/nickgaens/Desktop/April Morning [2928 × 1952] [OC].jpg'
Deleting desktop symlink '/Users/nickgaens/Desktop/Pink Flowers in Regents Park, London [OC][6000x4000].jpg'
Total candidate images: 13
   Ranking     Score    Aspect       Res    Reddit    Jitter Title
========================================================================================================================
        13      0.44      0.83      0.15      0.70      0.09 Knightville, South Portland, Maine [OC] [3264x2446]
        12      0.46      0.50      0.28      0.85      0.22 Nighttime Light, [1080 x 1350].
        11      0.47      0.82      0.17      0.66      0.24 [1012x767] [OC] Sweden, stockholm suburbs hässelby
        10      0.48      0.94      0.13      0.78      0.06 Iris in the garden [oc] [2038x1365]
         9      0.50      0.90      0.40      0.61      0.10 Spring in the Arctic [oc] [1920x1080]
         8      0.53      0.94      1.00      0.00      0.17 Star Shaped Lover's, in London [OC] [6000X4000]
         7      0.57      0.94      0.51      0.74      0.09 A blooming California purplehead field in Ventura County [200...
         6      0.58      0.47      1.00      0.78      0.06 2448x3264 Spring is here. When the temp is just right, it can...
         5      0.65      0.94      1.00      0.61      0.04 Emerging to reveal its beauty, Regents Park, London[OC] [6000...
         4      0.67      0.94      1.00      0.61      0.11 Hidden in Holland Park, London [OC][6000x4000]
         3      0.70      0.94      1.00      0.81      0.05 Birds eye view of a bright flower [OC] [6000X4000]
         2      0.76      0.94      1.00      0.91      0.20 Pink Flowers in Regents Park, London [OC][6000x4000]
         1      0.77      0.94      1.00      1.00      0.14 April Morning [2928 × 1952] [OC]
Number of images to download: 1
Downloading 'https://i.redditmedia.com/Oj7SezHAgVDZsUveq9wpcmGORTtnV9N-ukhReB27iow.jpg?s=db891ca4f0ff5138a8c30624b75f30de' to '/Users/nickgaens/Reddit Backgrounds/Desktop 1/April Morning [2928 × 1952] [OC].jpg'
Setting background for desktop 1
Total candidate images: 13
   Ranking     Score    Aspect       Res    Reddit    Jitter Title
========================================================================================================================
        13      0.48      0.84      1.00      0.00      0.09 Star Shaped Lover's, in London [OC] [6000X4000]
        12      0.51      0.75      0.38      0.78      0.12 Knightville, South Portland, Maine [OC] [3264x2446]
        11      0.52      0.74      0.43      0.70      0.23 [1012x767] [OC] Sweden, stockholm suburbs hässelby
        10      0.54      0.84      0.34      0.74      0.24 Iris in the garden [oc] [2038x1365]
         9      0.54      0.45      0.70      0.81      0.21 Nighttime Light, [1080 x 1350].
         8      0.57      0.42      1.00      0.81      0.06 2448x3264 Spring is here. When the temp is just right, it can...
         7      0.60      0.84      1.00      0.51      0.06 Emerging to reveal its beauty, Regents Park, London[OC] [6000...
         6      0.65      0.84      1.00      0.74      0.03 Birds eye view of a bright flower [OC] [6000X4000]
         5      0.66      0.84      1.00      0.66      0.16 Hidden in Holland Park, London [OC][6000x4000]
         4      0.67      0.84      1.00      0.78      0.06 A blooming California purplehead field in Ventura County [200...
         3      0.71      1.00      1.00      0.70      0.15 Spring in the Arctic [oc] [1920x1080]
         2      0.75      0.84      1.00      0.94      0.20 Pink Flowers in Regents Park, London [OC][6000x4000]
         1      0.76      0.84      1.00      1.00      0.19 April Morning [2928 × 1952] [OC]
Number of images to download: 1
'April Morning [2928 × 1952] [OC].jpg' already downloaded, skipping...
Downloading 'https://i.redditmedia.com/8LqraEwidzGzNUgj3827x7XoLAoikzUwk0glq5b8caA.jpg?s=9d7395adc6bfcd36048c77cbb52e3a49' to '/Users/nickgaens/Reddit Backgrounds/Desktop 2/Pink Flowers in Regents Park, London [OC][6000x4000].jpg'
Setting background for desktop 2
Total candidate images: 13
   Ranking     Score    Aspect       Res    Reddit    Jitter Title
========================================================================================================================
        13      0.48      0.84      1.00      0.00      0.06 Star Shaped Lover's, in London [OC] [6000X4000]
        12      0.48      0.75      0.38      0.72      0.06 Knightville, South Portland, Maine [OC] [3264x2446]
        11      0.51      0.45      0.70      0.87      0.01 Nighttime Light, [1080 x 1350].
        10      0.51      0.74      0.43      0.72      0.15 [1012x767] [OC] Sweden, stockholm suburbs hässelby
         9      0.52      0.84      0.34      0.84      0.05 Iris in the garden [oc] [2038x1365]
         8      0.57      0.42      1.00      0.80      0.06 2448x3264 Spring is here. When the temp is just right, it can...
         7      0.64      0.84      1.00      0.63      0.10 Emerging to reveal its beauty, Regents Park, London[OC] [6000...
         6      0.67      0.84      1.00      0.72      0.13 Hidden in Holland Park, London [OC][6000x4000]
         5      0.70      0.84      1.00      0.84      0.12 Birds eye view of a bright flower [OC] [6000X4000]
         4      0.71      0.84      1.00      0.80      0.21 A blooming California purplehead field in Ventura County [200...
         3      0.73      0.84      1.00      0.97      0.13 Pink Flowers in Regents Park, London [OC][6000x4000]
         2      0.74      1.00      1.00      0.80      0.15 Spring in the Arctic [oc] [1920x1080]
         1      0.77      0.84      1.00      1.00      0.22 April Morning [2928 × 1952] [OC]
Number of images to download: 1
'April Morning [2928 × 1952] [OC].jpg' already downloaded, skipping...
Downloading 'https://i.redditmedia.com/poNYyAGsQNLnj-3cSkJjNLWA7RPJomOYVqzyromzCkc.png?s=847a8bb8fe2cdbb81f1518bf64ae9405' to '/Users/nickgaens/Reddit Backgrounds/Desktop 3/Spring in the Arctic [oc] [1920x1080].png'
Setting background for desktop 3
```
