### ISSUE TITLE
I am a bit of a noob. When I try to run the program I get this error.

### ISSUE THREAD

**Issue by rylentless** [rconradharris/reddit-background#26]
/Users/blank/reddit-backgrounds/reddit-background ; exit;
Traceback (most recent call last):
  File "/Users/blank/reddit-backgrounds/reddit-background", line 791, in <module>
    main()
  File "/Users/blank/reddit-backgrounds/reddit-background", line 763, in main
    _read_config_file(desktops)
  File "/Users/blank/reddit-backgrounds/reddit-background", line 682, in _read_config_file
    set_desktop_symlink(config.getboolean('default', 'desktop_symlink'))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ConfigParser.py", line 370, in getboolean
    raise ValueError, 'Not a boolean: %s' % v
ValueError: Not a boolean: True  # Symlink will show filename/title on desktop
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

**Comment by BetaStacks** [comment]
I'm having thee same problem. Did you figure out how to resolve this?

**Comment by pelomedusa** [comment]
You have to remove the comment in your config file next to : 
desktop_symlink = False

**Comment by rconradharris** [comment]
@rylentless @pelomedusa Yeah looks like the syntax in the example is broken. Removing the comment should fix that. I'll update the example to move the comment up to the previous line.
