### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by BetaStacks** [rconradharris/reddit-background#27]
I get this error when I run `./reddit-background`

Traceback (most recent call last):
  File "./reddit-background", line 791, in <module>
    main()
  File "./reddit-background", line 762, in main
    desktops = _get_desktops_with_defaults()
  File "./reddit-background", line 470, in _get_desktops_with_defaults
    for num, res in enumerate(_OS_HANDLER.get_desktop_resolutions(), start=1):
  File "./reddit-background", line 206, in get_desktop_resolutions
    import Xlib.display
ImportError: No module named Xlib.display

**Comment by Yabk** [comment]
You need to install python xlib
`sudo apt install python-xlib`

**Comment by BetaStacks** [comment]
Thanks! 
I installed python-xlib and now the output is: 

`pi@201:~/reddit-backgrounds $ ./reddit-background
Xlib.protocol.request.QueryExtension
Traceback (most recent call last):
  File "./reddit-background", line 791, in <module>
    main()
  File "./reddit-background", line 787, in main
    desktop.set_background(paths[0])
  File "./reddit-background", line 455, in set_background
    _OS_HANDLER.set_background(path, num=self.num)
  File "./reddit-background", line 200, in set_background
    if subprocess.call(cmd):
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory`

**Comment by sogaiu** [comment]
FWIW, I got a similar error and installing feh got me further along.
