### ISSUE TITLE
Linux, cannot set background

### ISSUE THREAD

**Issue by codemonkeybr** [rconradharris/reddit-background#39]
using the background example, gives me an error about setting up the background, because it downloads but the wallpaper doesnt change.

`~ reddit-background --download-directory /home/tesso/reddit-backgrounds/images/           
Traceback (most recent call last):
  File "/usr/bin/reddit-background", line 1009, in <module>
    main()
  File "/usr/bin/reddit-background", line 1006, in main
    desktop.set_background(paths[0])
  File "/usr/bin/reddit-background", line 507, in set_background
    _OS_HANDLER.set_background(path, num=self.num)
  File "/usr/bin/reddit-background", line 190, in set_background
    if subprocess.call(cmd):
  File "/usr/lib/python2.7/subprocess.py", line 523, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

`

what can i do to get more info to fix this error?

**Comment by rickardcronholm** [comment]
I have the exact same issue on ubuntu 17.10

**Comment by bdonvr** [comment]
Install the `feh`  package. On Ubuntu run `sudo apt install feh` and on Arch it should be `sudo pacman -S feh` but it's been a while since I've been on Arch. 

Note that doing that made the error go away for me but it still doesn't change the background for me on Ubuntu 18.04.
