### ISSUE TITLE
URL lib error

### ISSUE THREAD

**Issue by rconradharris** [rconradharris/reddit-background#4]
Subject: Cron rick@Richards-MacBook-Pro /usr/local/bin/reddit-background
X-Cron-Env: <SHELL=/bin/sh>
X-Cron-Env: <PATH=/usr/bin:/bin>
X-Cron-Env: <LOGNAME=rick>
X-Cron-Env: <USER=rick>
X-Cron-Env: <HOME=/Users/rick>
Date: Tue, 12 May 2015 10:03:35 -0500 (CDT)

Traceback (most recent call last):
  File "/usr/local/bin/reddit-background", line 392, in <module>
    main()
  File "/usr/local/bin/reddit-background", line 388, in main
    desktop.set_background()
  File "/usr/local/bin/reddit-background", line 167, in set_background
    _choose_and_set_background_from_urls(self.num, image_urls)
  File "/usr/local/bin/reddit-background", line 140, in _choose_and_set_background_from_urls
    filename = _download_image(image_url)
  File "/usr/local/bin/reddit-background", line 101, in _download_image
    response = _urlopen(image_url)
  File "/usr/local/bin/reddit-background", line 80, in _urlopen
    return opener.open(url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1214, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 8] nodename nor servname provided, or not known>

**Comment by awendland** [comment]
When you run the program again does the error appear? I remember getting this once while running the script; in my case it was complaining because Reddit returned a 503 error code.
