### ISSUE TITLE
Uncaught Exception

### ISSUE THREAD

**Issue by rconradharris** [rconradharris/reddit-background#5]
Traceback (most recent call last):
  File "/usr/local/bin/reddit-background", line 392, in <module>
    main()
  File "/usr/local/bin/reddit-background", line 388, in main
    desktop.set_background()
  File "/usr/local/bin/reddit-background", line 163, in set_background
    urls = subreddit.fetch_image_urls()
  File "/usr/local/bin/reddit-background", line 238, in fetch_image_urls
    posts = self._fetch_posts()
  File "/usr/local/bin/reddit-background", line 222, in _fetch_posts
    response = _urlopen(url)
  File "/usr/local/bin/reddit-background", line 80, in _urlopen
    return opener.open(url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 442, in error
    result = self._call_chain(_args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(_args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 629, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(_args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(_args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 503: Service Unavailable

**Comment by rconradharris** [comment]
The fix for #4 should also fix this.
