### ISSUE TITLE
Error when running under CRON

### ISSUE THREAD

**Issue by sam-lewis** [rconradharris/reddit-background#6]
I am running Yosemite 10.10.5 and am using the latest script from master. It works great when in run from the terminal but it fails from cron:

```
Date: Fri, 19 Feb 2016 09:00:00 +0000 (GMT)

Traceback (most recent call last):
  File "/usr/local/bin/reddit-background", line 411, in <module>
    main()
  File "/usr/local/bin/reddit-background", line 393, in main
    _handle_cli_options(desktop_info)
  File "/usr/local/bin/reddit-background", line 358, in _handle_cli_options
    desktops = range(1, len(_get_desktops()) + 1)
  File "/usr/local/bin/reddit-background", line 108, in _get_desktops
    p = subprocess.Popen(["system_profiler", "SPDisplaysDataType"], stdout=subprocess.PIPE)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by hoombar** [comment]
I'm seeing the same issue with the same stack trace, but I'm running El Capitan.

**Comment by hoombar** [comment]
@sam-lewis you need to set up your path in crontab, this is an environment issue, not a script issue. @rconradharris perhaps the README should be updated? I could submit a PR for this if you want.

First, get your path: `echo $PATH` then add your path to the start of your crontab

```
echo $PATH
/opt/local/bin:/opt/local/sbin:/opt/local/bin:/opt/local/sbin (for example)
```

crontab -l

```
PATH=/opt/local/bin:/opt/local/sbin:/opt/local/bin:/opt/local/sbin

0 9 * * * /usr/local/bin/python /usr/local/bin/reddit-background
```

This worked for me.

**Comment by sam-lewis** [comment]
@hoombar Thanks - worked for me
